# taxonomy.py

UCP_CATEGORIES = {
    "multiword expression": "multiword expression, i.e., fully lexicalized fixed expressions, e.g. by and large, in short",
    "multiword_unit_idiomatic_expression": "multiword unit: idiomatic expression (e.g., kick the bucket, let the cat out of the bag)",
    "mwe_compound_nominal": "multiword expression: compound nominal (e.g, car park)",
    "mwe_proper_name": "multiword expression: proper name",
    "mwe_light_verb_construction": "multiword expression: light-verb construction (e.g., make a mistake, give a demo)",
    "mwe_verb_particle_construction": "multiword expression: verb-particle construction (e.g., write up, look up)",
    "mwe_institutionalised_phrase": "multiword expression: institutionalised/conventionalised phrase (e.g., salt and pepper) ",
    "complex_noun_phrase": "complex noun phrase",
    "complex_syntactic_structure": "complex syntactic structure",
    "metaphor_and_original_image": "metaphor and/or original image; a figure of speech that implicitly compares two unrelated things, typically by stating that one thing is another.",
    "comparison": "comparison",
    "wordplay_and_puns": "wordplay and puns",
    "onomatopoeias": "onomatopoeias",
    "colloquial_language": "colloquial language (e.g., cursing, slang, colloquial constructions)",
    "cultural_and_historical_reference": "cultural and historical reference",
    "neologism": "neologism",
    "gender_issue": "gender issue (e.g., president vs secratary in languages with gender cases)",
    "linguistic_variant": "linguistic variant (e.g., American English or UK English)",
    "unusual_punctuation": "unusual punctuation",
    "rhyme_and_metrics": "rhyme and metrics",
    "treatment": "treatment (e.g., formal, informal)",
    "other": "other",
}

TRANSLATION_TECHNIQUES = {
    "literal": "word-for-word translation (including insertion or deletion of determiners, changes between singular and plural forms), or possible literal translation of some idioms; the underlying syntactic construction is similar in both languages",
    "equivalence": "Non-literal translation of proverbs, idioms, fixed expressions or syntactical constructioons (which  cannot be transferred as such into the target langauge) OR semantic equivalence at the supra-lexical level, translation of terms.",
    "modulation_particularization": "The translation is more precise or presents a more concrete sense.",
    "modulation_generalization": "The translation is more general or neutral OR translation of an idiom by a non-fixed expression OR removal of a metaphorical image.",
    "modulation_other": "Changing the point of view, either to circumvent a translation difficulty or to reveal a way of seeing things.",
    "transposition": "Translating words or expressions by using other grammatical categories (e.g., noun -> verb) than the ones used in the source language, without altering the meaning of the utterance.",
    "modulation_plus_transposition": "Any sub-type of Modulation combined with transposition",
    "metaphor": "Keep the same metaphorical image by using a non-literal translation OR introduce metaphorical expression to translate non-metaphor",
    "idiom": "Translate non-fixed expression by an idiom.",
    "reduction": "Remove deliberately certain content words in translation",
    "explicitation": "Introduce clarifications that remain implicit in the source language.",
    "no_type_attributed": "Translated words which don't correspond to any source words",
    "erroneous": "Obvious translation error.",
    "untranslated": "Keep the source in the target to avoid the translation problem.",
    "uncertain": "Difficult example (not clear from attotation guidelines how to annotate this example).",
}